version: '3'
services:
  client:
    # container_name: client
    image: client:latest
    networks:
      - distribuidos-tp2_testing_net
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/data
    deploy:
      replicas: 2

networks:
  distribuidos-tp2_testing_net:
    external: true
