version: '3'
services:
  client1:
    # container_name: client
    image: client:latest
    networks:
      - distribuidos-tp2_testing_net
    environment:
      - PYTHONUNBUFFERED=1
      - ID=1
    volumes:
      - ./data:/data

  client2:
    # container_name: client
    image: client:latest
    networks:
      - distribuidos-tp2_testing_net
    environment:
      - PYTHONUNBUFFERED=1
      - ID=2
    volumes:
      - ./data:/data

networks:
  distribuidos-tp2_testing_net:
    external: true
